version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - store_artifacts:
            path: calculator-release.apk
            destination: app-to-test
  test:
    docker:
      - image: hirvijo/robot:1.1
    steps:
      - checkout
      - run: robot --variable APP:$CIRCLE_ARTIFACTS/app-to-test .
    requires:
      - build
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
