version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - store_artifacts:
            path: calculator-release.apk
            destination: app-to-test
      - run: mkdir -p workspace
      - run: echo $CIRCLE_BUILD_NUM > workspace/android-build-number
      - persist_to_workspace:
          root: workspace
          paths:
            - android-build-number
  test:
    docker:
      - image: hirvijo/robot:1.1
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: 
          name: Read file and set as environment variable BUILD_NUMBER
          command: echo 'export BUILD_NUMBER=$(cat /tmp/workspace/android-build-number)' >> $BASH_ENV
      - run: 
          name: Run tests
          command: robot -d tmp/report .
          environment:
            HUB: https://f2f2850c.ngrok.io/wd/hub
      - store_artifacts:
            path: tmp/report
            destination: report
workflows:
  version: 2
  commit:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - test:
          requires:
            - hold
  nightly:
    jobs:
      - test
    triggers:
      - schedule:
          cron: "* 12 10 * *"
          filters:
            branches:
              only: 
                - master
