version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - store_artifacts:
            path: calculator-release.apk
            destination: app-to-test
  test:
    docker:
      - image: hirvijo/robot:1.1
    steps:
      - checkout
      - run: echo THIS IS IT $CIRCLE_ARTIFACTS
      - run: robot --variable APP:"https://18-145885837-gh.circle-artifacts.com/0/app-to-test" .
    requires:
      - build
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
