version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - store_artifacts:
            path: calculator-release.apk
            destination: app-to-test
  test:
    docker:
      - image: hirvijo/robot:1.1
    steps:
      - checkout
      - run: robot -d tmp/report --variable APP:"https://18-145885837-gh.circle-artifacts.com/0/app-to-test" .
            no_output_timeout: 5m
      - store_artifacts:
            path: tmp/report
            destination: report
workflows:
  version: 2
  commit:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - test:
          requires:
            - hold
  nightly:
    jobs:
      - test
    triggers:
      - schedule:
          cron: "* * 1 * *"
          filters:
            branches:
              only: 
                - master
