version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - store_artifacts:
            path: calculator-release.apk
            destination: artifact-file
  test:
    docker:
      - image: hirvijo/robot:1.1
    steps:
      - checkout
      - run: robot .
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
