version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - store_artifacts:
            path: calculator-release.apk
            destination: app-to-test
      - run: mkdir -p workspace
      - run: echo $CIRCLE_BUILD_NUM > workspace/android-build-number
      - persist_to_workspace:
          root: workspace
          paths:
            - android-build-number
  test:
    docker:
      - image: circleci/python:2.7.14
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Install dependencies
          command: |
            pip install robotframework == 3.0.4
            pip install robotframework-seleniumlibrary == 3.1.1
            pip install robotframework-appiumlibrary == 1.4.6
            pip install robotframework-requests == 0.4.7
            pip install selenium == 3.14.0
            pip install requests == 2.19.1
      - run: 
          name: Define environment variable BUILD_NUMBER
          command: echo 'export BUILD_NUMBER=$(cat /tmp/workspace/android-build-number)' >> $BASH_ENV
      - run: 
          name: Run tests
          command: robot -d tmp/report .
          environment:
            HUB: https://314e595d.ngrok.io/wd/hub
      - store_artifacts:
            path: tmp/report
            destination: report
workflows:
  version: 2
  commit:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - test:
          requires:
            - hold
  nightly:
    jobs:
      - test
    triggers:
      - schedule:
          cron: "* 12 10 * *"
          filters:
            branches:
              only: 
                - master
