version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - store_artifacts:
            path: calculator-release.apk
            destination: app-to-test
      - run: mkdir -p workspace
      - run: echo $CIRCLE_BUILD_NUM > workspace/echo-output
      - persist_to_workspace:
          root: workspace
          paths:
            - echo-output
  test:
    docker:
      - image: hirvijo/robot:1.1
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: cat /tmp/workspace/echo-output
      - run:
          name: Define Environment Variable at Runtime
          command: |
            echo 'export BUILD_NUMBER=$(cat /tmp/workspace/echo-output)' >> $BASH_ENV
      - run: 
          name: run tests
          command: robot -d tmp/report --variable APP:"https://18-145885837-gh.circle-artifacts.com/0/app-to-test" .
      - store_artifacts:
            path: tmp/report
            destination: report
workflows:
  version: 2
  commit:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - test:
          requires:
            - hold
  nightly:
    jobs:
      - test
    triggers:
      - schedule:
          cron: "* 12 10 * *"
          filters:
            branches:
              only: 
                - master
